- hosts: proxmox_servers
  tasks:
    - include_role:
        name: install_base_packages
        apply:
          tags:
            - install_base_packages
      tags:
        - install_base_packages

    - include_role:
        name: create_terraform_user
        apply:
          tags:
            - create_terraform_user
      tags:
        - create_terraform_user

    - include_role:
        name: install_postfix
        apply:
          tags:
            - install_postfix
      tags:
        - install_postfix

    - include_role:
        name: install_sanoid
        apply:
          tags:
            - install_sanoid
      tags:
        - install_sanoid

    - include_role:
        name: install_unattended_upgrades
        apply:
          tags:
            - install_unattended_upgrades
      tags:
        - install_unattended_upgrades

    - include_role:
        name: configure_zed
        apply:
          tags:
            - configure_zed
      tags:
        - configure_zed

    - include_role:
        name: enable_iommu
        apply:
          tags:
            - enable_iommu
      tags:
        - enable_iommu
