---
- name: Installing an email and smtp relay client
  apt:
    state: present
    name:
    - unattended-upgrades
    - apt-listchanges
  when:
    - CONFIGURE_UNATTENDED_UPGRADES == "true"

- name: Configuring SMTP notifications for unattended upgrades
  lineinfile:
      path: /etc/apt/apt.conf.d/50unattended-upgrades
      regexp: '/?/?Unattended-Upgrade::Mail .*'
      line: 'Unattended-Upgrade::Mail "{{ VAR_UPGRADES_EMAIL |lower }}";'
      backrefs: yes
  when:
    - VAR_UPGRADES_EMAIL != ""
    - VAR_UPGRADES_NOTIFY == "true"
  notify:
    - Restarting unattended-upgrades

- name: Configuring when unattended upgrade notifications are sent
  lineinfile:
      path: /etc/apt/apt.conf.d/50unattended-upgrades
      regexp: '/?/?Unattended-Upgrade::MailOnlyOnError.*'
      line: 'Unattended-Upgrade::MailOnlyOnError true;'
      backrefs: yes
  when:
    - VAR_UPGRADES_NOTIFY == "true"
    - VAR_UPGRADES_NOTIFY_ON_ERROR == "true" or VAR_UPGRADES_NOTIFY_ON_ERROR == "false"
  notify:
    - Restarting unattended-upgrades

- name: Restricting updates to only occur during a graceful shutdown
  lineinfile:
    path: /etc/apt/apt.conf.d/50unattended-upgrades
    regexp: '/?/?Unattended-Upgrade::InstallOnShutdown.*'
    line: 'Unattended-Upgrade::InstallOnShutdown true;'
    backrefs: yes
  when:
    - VAR_UPGRADES_ON_SHUTDOWN == "true"
  notify:
    - Restarting unattended-upgrades

- name: Configuring unattended upgrades to remove unused kernel packages
  lineinfile:
    path: /etc/apt/apt.conf.d/50unattended-upgrades
    regexp: '/?/?Unattended-Upgrade::Remove-Unused-Kernel-Packages.*'
    line: 'Unattended-Upgrade::Remove-Unused-Kernel-Packages true;'
    backrefs: yes
  when:
    - VAR_UPGRADES_UNUSED_K_PAC == "true"
  notify:
    - Restarting unattended-upgrades

- name: Configuring unattended upgrades to remove unused package dependencies
  lineinfile:
    path: /etc/apt/apt.conf.d/50unattended-upgrades
    regexp: '/?/?Unattended-Upgrade::Remove-Unused-Dependencies.*'
    line: 'Unattended-Upgrade::Remove-Unused-Dependencies true;'
    backrefs: yes
  when:
    - VAR_UPGRADES_UNUSED_DEP == "true"
  notify:
    - Restarting unattended-upgrades

- name: Configuring unattended upgrades to automatically reboot the node
  lineinfile:
    path: /etc/apt/apt.conf.d/50unattended-upgrades
    regexp: '/?/?Unattended-Upgrade::Automatic-Reboot .*'
    line: 'Unattended-Upgrade::Automatic-Reboot true;'
    backrefs: yes
  when:
    - VAR_UPGRADES_AUTO_REBOOT == "true"
  notify:
    - Restarting unattended-upgrades

- name: Configuring unattended upgrades to automatically reboot the node specifically at {{ VAR_UPGRADES_AUTO_REBOOT_TIME }}
  lineinfile:
    path: /etc/apt/apt.conf.d/50unattended-upgrades
    regexp: '/?/?Unattended-Upgrade::Automatic-Reboot-Time.*'
    line: 'Unattended-Upgrade::Automatic-Reboot-Time "{{ VAR_UPGRADES_AUTO_REBOOT_TIME }}";'
    backrefs: yes
  when:
    - VAR_UPGRADES_AUTO_REBOOT == "true"
    - VAR_UPGRADES_AUTO_REBOOT_TIME != ""
  notify:
    - Restarting unattended-upgrades

- name: Configuring unattended upgrades to log to syslog.
  lineinfile:
    path: /etc/apt/apt.conf.d/50unattended-upgrades
    regexp: '/?/? ?Unattended-Upgrade::SyslogEnable.*'
    line: 'Unattended-Upgrade::SyslogEnable true;'
    backrefs: yes
  when:
    - VAR_UPGRADES_LOG_SYSLOG == "true"
  notify:
    - Restarting unattended-upgrades
