---
- hosts: proxmox
  become: true
  gather_facts: false
  tasks:
    - import_role:
        name: Configure_Proxmox
      vars:
        # Configure Tasks
        CONFIGURE_REPOSITORIES: "{{ lookup('env', 'TKS_BP_T_CONFIGURE_REPOSITORIES') | default('false') }}"
        CONFIGURE_UNATTENDED_UPGRADES: "{{ lookup('env', 'TKS_BP_T_CONFIGURE_UNATTENDED_UPGRADES') | default('false') }}"
        CONFIGURE_SYSTEM: "{{ lookup('env', 'TKS_BP_T_CONFIGURE_SYSTEM') }}"
        CONFIGURE_ZFS: "{{ lookup('env', 'TKS_BP_T_CONFIGURE_ZFS') }}"
        #
        #
        # Install Tasks
        INSTALL_PACKAGES: "{{ lookup('env', 'TKS_BP_T_INSTALL_PACKAGES') }}"
        INSTALL_SANOID: "{{ lookup('env', 'TKS_BP_T_INSTALL_SANOID') }}"
        INSTALL_POSTFIX: "{{ lookup('env', 'TKS_BP_T_INSTALL_POSTFIX') }}"
        # INSTALL_ZSH: "{{ lookup('env', 'TKS_BP_T_INSTALL_ZSH') }}"
        #
        #
        # Postfix Variables
        VAR_POSTFIX_SERVER: "{{ lookup('env', 'TKS_BP_V_POSTFIX_SERVER') | default('smtp.gmail.com') }}"
        VAR_POSTFIX_PORT: "{{ lookup('env', 'TKS_BP_V_POSTFIX_PORT') | default('587') }}"
        VAR_POSTFIX_TLS: "{{ lookup('env', 'TKS_BP_V_POSTFIX_TLS') | default('yes') }}"
        VAR_POSTFIX_EMAIL: "{{ lookup('env', 'TKS_BP_V_POSTFIX_EMAIL') }}"
        VAR_POSTFIX_PASSWORD: "{{ lookup('env', 'TKS_BP_V_POSTFIX_PASSWORD') }}"
        #
        #
        # Unattended Upgrades Variables
        VAR_UPGRADES_NOTIFY: "{{ lookup('env', 'TKS_BP_V_UPGRADES_NOTIFY') | default('true') }}"
        VAR_UPGRADES_NOTIFY_ON_ERROR: "{{ lookup('env', 'TKS_BP_V_UPGRADES_NOTIFY_ON_ERROR') | default('false') }}"
        VAR_UPGRADES_EMAIL: "{{ lookup('env', 'TKS_BP_V_UPGRADES_EMAIL') }}"
        VAR_UPGRADES_UNUSED_DEP: "{{ lookup('env', 'TKS_BP_V_UPGRADES_UNUSED_DEP') | default('false') }}"
        VAR_UPGRADES_UNUSED_K_PAC: "{{ lookup('env', 'TKS_BP_V_UPGRADES_UNUSED_K_PAC') | default('false') }}"
        VAR_UPGRADES_AUTO_REBOOT: "{{ lookup('env', 'TKS_BP_V_UPGRADES_AUTO_REBOOT') | default('false') }}"
        VAR_UPGRADES_AUTO_REBOOT_TIME: "{{ lookup('env', 'TKS_BP_V_UPGRADES_AUTO_REBOOT_TIME') | default('03:00') }}"
        VAR_UPGRADES_ON_SHUTDOWN: "{{ lookup('env', 'TKS_BP_V_UPGRADES_ON_SHUTDOWN') | default('true') }}"
        VAR_UPGRADES_LOG_SYSLOG: "{{ lookup('env', 'TKS_BP_V_UPGRADES_LOG_SYSLOG') | default('true') }}"
        #
        #
        # System Variables
        VAR_SYS_SWAPPINESS: "{{ lookup('env', 'TKS_BP_V_SYS_SWAPPINESS') | default('10') }}"
        #
        #
        # ZFS Variables
        # VAR_ZFS_ARC_MAX: "{{ lookup('env', 'TKS_BP_V_ZFS_ARC_MAX' }}"
        VAR_ZFS_POOL_LIST: "{{ lookup('env', 'TKS_BP_V_ZFS_POOL_LIST') }}"
        #
        #
        # Sanoid Variables
        VAR_SANOID_VERSION: "{{ lookup('env', 'TKS_BP_V_SANOID_VERSION') | default('2.0.3') }}"
